### ISSUE TITLE
Responsive UI bugs

### ISSUE THREAD

**Issue by cbks-acc** [caseybanks/ms1-face-fodder#17]
To enhance UI experience on smaller screens I will fix the following:

- [x] 1. Remove sticky nav menu for screens smaller then 767px

- [x] 2. Reduce social media icons sizes to 32 px in footer

- [x] 3. Increase .form-group-details width to 100% for screens smaller then  576px

- [x] 4. add top padding to HOME DIY SOLUTIONS FOR ... image titles

**Comment by cbks-acc** [comment]
1. Added media query:
``` CSS
@media (max-width: 767px) {
    .sticky-top {
        position: inherit;
    }
}
```
2. Added media query:
``` CSS
@media (max-width: 576px) {
    .fab {
        font-size: 32px;
    }
}
```
3. Added media query:
``` CSS
@media (max-width: 576px) {
	.form-group-details {
		width: 100%;
	}
}
```

4. Created a new class and added a new media query:
```CSS
@media (max-width: 767px) {
    .home-diy-solution-title {
        padding-top: 20px;
    }
}
