### ISSUE TITLE
FF6: Add a :hover effect to the social icons

### ISSUE THREAD

**Issue by cbks-acc** [caseybanks/ms1-face-fodder#6]
- [ ] to make it more UI clear

**Comment by cbks-acc** [comment]
I added:
``` CSS
.fab:hover {
    color: #76686a;
}
```
to highlight the social icons when a user hovers over the icons.
